[info]
app_id = "Apparency"
name = "Apparency"
description = "macOS app 包信息查看工具"
official_website = "https://www.mothersruin.com/software/Apparency/"
platforms = ["macos"]

[config]
type = "html_selector"
url = "https://www.mothersruin.com/software/Apparency/get.html"
baseurl = "https://www.mothersruin.com"

[config.macos]
v_position = { selector = "td.version", regex = "(\\d+\\.\\d+)" }
d_position = { selector = "a.download-link", attr = "href" }
