[info]
app_id = "Blender"
name = "Blender"
description = "建模工具"
official_website = "https://www.blender.org/download/"
platforms = ["macos", "windows", "linux"]

[config]
type = "html_selector"
url = "https://www.blender.org/download/"

[config.macos]
d_position = { selector = "#macos a", attr = "href" }
v_position = { selector = "#macos a", attr = "href", regex = "blender-(.*)-macos" }

[config.windows]
d_position = { selector = "#windows a", attr = "href" }
v_position = { selector = "#windows a", attr = "href", regex = "blender-(.*)-windows" }

[config.linux]
d_position = { selector = "#linux a", attr = "href" }
v_position = { selector = "#linux a", attr = "href", regex = "blender-(.*)-linux" }
