[info]
app_id = "Chromium"
name = "Chromium"
description = "浏览器内核"
official_website = "https://download-chromium.appspot.com"
platforms = ["macos", "windows", "linux"]

[config]
type = "regex"
v_position = "(\\d+)"
d_type = "direct"

[config.macos]
v_url = "https://commondatastorage.googleapis.com/chromium-browser-snapshots/Mac_Arm/LAST_CHANGE"
d_url = "https://commondatastorage.googleapis.com/chromium-browser-snapshots/Mac_Arm/{version}/chrome-mac.zip"

[config.windows]
v_url = "https://commondatastorage.googleapis.com/chromium-browser-snapshots/Win_x64/LAST_CHANGE"
d_url = "https://commondatastorage.googleapis.com/chromium-browser-snapshots/Win_x64/{version}/chrome-win.zip"

[config.linux]
v_url = "https://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/LAST_CHANGE"
d_url = "https://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/{version}/chrome-linux.zip"
