[info]
app_id = "DevToys"
name = "DevToys"
description = "开发者工具箱"
official_website = "https://github.com/DevToys-app/DevToys/releases"
platforms = ["windows", "macos", "linux"]

[config]
type = "github"
owner = "DevToys-app"
repo = "DevToys"
allow_prerelease = true

[config.windows]
d_position = "devtoys_win_x64.*exe$"

[config.macos]
d_position = "devtoys_osx_arm64.*zip$"

[config.linux]
d_position = "devtoys_linux_x64.*deb$"
