[info]
app_id = "OracleJDK8"
name = "Oracle JDK 8"
description = "Oracle Java SE Development Kit 8"
official_website = "https://www.oracle.com/java/technologies/downloads/#java8"
platforms = ["macos", "windows", "linux"]

[config]
type = "html_selector"
url = "https://www.oracle.com/java/technologies/downloads/"
v_position = { selector = "#java8 h2", regex = "Java SE Development Kit (8u[0-9]+)" }
d_type = "direct"
d_url = "https://www.oracle.com/java/technologies/downloads/#java8"
