[info]
app_id = "Python"
name = "Python"
description = "Python"
official_website = "https://www.python.org/downloads/"
platforms = ["macos", "windows", "linux"]

[config]
type = "html_selector"
url = "https://www.python.org/downloads/"
v_position = { selector = ".download-buttons a[href*='ftp']", regex = "Python (.*)" }

[config.macos]
ua = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36"
d_position = { selector = ".download-buttons a[href*='pkg']", attr = "href" }


[config.windows]
ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.7727.56 Safari/537.36"
d_position = { selector = ".download-buttons a[href*='msix']", attr = "href" }


[config.linux]
ua = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36"
d_position = { selector = ".download-buttons a[href*='tar.xz']", attr = "href" }
