[info]
app_id = "SourceGit"
name = "SourceGit"
description = "可视化Git客户端"
official_website = "https://github.com/sourcegit-scm/sourcegit/releases"
platforms = ["macos", "windows", "linux"]

[config]
type = "github"
owner = "sourcegit-scm"
repo = "sourcegit"

[config.macos]
d_position = "osx-arm64"

[config.windows]
d_position = "win-x64"

[config.linux]
d_position = "amd64.AppImage$"
