[info]
app_id = "163MusicLyrics"
name = "163MusicLyrics"
description = "网易云音乐歌词下载器"
official_website = "https://github.com/jitwxs/163MusicLyrics/releases"
platforms = ["macos", "windows", "linux"]

[config]
type = "github"
owner = "jitwxs"
repo = "163MusicLyrics"

[config.macos]
d_position = "osx-arm64"

[config.windows]
d_position = "win-x64"

[config.linux]
d_position = "linux"
