[info]
app_id = "Autoruns"
name = "Autoruns"
description = "自启动项管理工具"
official_website = "https://learn.microsoft.com/zh-cn/sysinternals/downloads/autoruns"
platforms = ["windows"]

[config]
type = "html_selector"
url = "https://learn.microsoft.com/zh-cn/sysinternals/downloads/autoruns"

[config.windows]
v_position = { selector = "h1", regex = "Autoruns v([\\d.]+)" }
d_position = { selector = "a[href*='Autoruns.zip']", attr = "href" }
