[info]
app_id = "CloudflareWARP"
name = "Cloudflare WARP"
description = "Cloudflare"
official_website = "https://one.one.one.one/"
platforms = ["macos", "windows"]

[config]
type = "html_selector"
v_type = "direct"
v_url = "Latest"
url = "https://one.one.one.one/"

[config.macos]
d_position = { selector = "a[href*='mac/latest']", attr = "href" }

[config.windows]
d_position = { selector = "a[href*='win/latest']", attr = "href" }
