[info]
app_id = "GeoGebraCalculatorSuite"
name = "GeoGebra Calculator Suite"
description = "科学和图形计算器套件"
official_website = "https://www.geogebra.org/download"
platforms = ["macos", "windows"]

[config]
type = "json"
url = "https://geogebra.github.io/docs/reference/en/GeoGebra_Installation/"
v_url = "https://api.github.com/repos/microsoft/winget-pkgs/contents/manifests/g/GeoGebra/CalculatorSuite"
v_position = [-1, "name"]
d_type = "html_selector"

[config.macos]
d_position = { selector = "a[href$='mac-suite-portable']", attr = "href" }

[config.windows]
d_position = { selector = "a[href$='win-suite']", attr = "href" }
