[info]
app_id = "gMKVExtractGUI"
name = "gMKVExtractGUI"
description = "提取MKV轨道工具"
official_website = "https://sourceforge.net/projects/gmkvextractgui/"
platforms = ["windows", "extra"]

[config]
type = "regex"
url = "https://sourceforge.net/p/gmkvextractgui/activity/feed"
v_position = "<title>gMKVExtractGUI released /v([^/]+)/gMKVExtractGUI.*</title>"
ua = "curl/8.0.0"

[config.windows]
d_type = "direct"
d_url = "https://sourceforge.net/projects/gmkvextractgui/files/latest/download"

[config.extra]
d_type = "direct"
d_url = "https://sourceforge.net/projects/gmkvextractgui/files/v{version}/gMKVExtractGUI.locales.v{version}.zip/download"
