[info]
app_id = "Huorong"
name = "火绒安全软件"
description = "杀毒软件"
official_website = "https://www.huorong.cn/"
platforms = ["windows"]

[config]
type = "html_selector"
url = "https://www.huorong.cn/"
v_position = { selector = ".std_title6", regex = "火绒安全软件(\\d+\\.\\d+)" }

[config.windows]
d_position = { selector = "a[data-url*='x64UrlAll']", attr = "data-url" }
