[info]
app_id = "Mp3tag"
name = "Mp3tag"
description = "音频标签编辑器"
official_website = "https://www.mp3tag.de/download.html"
platforms = ["windows"]

[config]
type = "html_selector"
url = "https://www.mp3tag.de/download.html"
baseurl = "https://www.mp3tag.de/"
v_position = { selector = ".sections h2", regex = "Mp3tag v([0-9]+\\.[0-9]+\\.[0-9]+)" }

[config.windows]
d_position = { selector = "a[title*='x64']", attr = "href" }
