[info]
app_id = "MTManager"
name = "MT管理器"
description = "APK 修改与文件管理工具"
official_website = "https://mt2.cn/download/"
platforms = ["android"]

[config]
type = "html_selector"
url = "https://mt2.cn/download/"

[config.android]
v_position = { selector = ".content__default", regex = "版本名：v([0-9.]+)" }
d_position = { selector = "a[href*='pan.mt2.cn/apk/']", attr = "href" }
