[info]
app_id = "OmniDiskSweeper"
name = "OmniDiskSweeper"
description = "磁盘空间分析软件"
official_website = "https://www.omnigroup.com/more"
platforms = ["macos"]

[config]
type = "html_selector"
url = "https://www.omnigroup.com/more"
baseurl = "https://www.omnigroup.com/"
v_type = "direct"
v_url = "Latest"

[config.macos]
d_position = { selector = ".download a[href*='OmniDiskSweeper']", attr = "href" }
