[info]
app_id = "RemoteDesktopManager"
name = "Remote Desktop Manager"
description = "远程连接管理工具"
official_website = "https://devolutions.net/remote-desktop-manager/download/"
platforms = ["windows", "macos", "linux"]

[config]
type = "html_selector"
url = "https://devolutions.net/remote-desktop-manager/download/"

[config.windows]
v_position = { selector = "[data-dl-section=\"rdm-windows\"] a", attr = "data-g-version" }
d_position = { selector = "[data-dl-section=\"rdm-windows\"] a[data-g-extension=\"exe\"]", attr = "href" }

[config.macos]
v_position = { selector = "[data-dl-section=\"rdm-macos\"] a", attr = "data-g-version" }
d_position = { selector = "[data-dl-section=\"rdm-macos\"] a", attr = "href" }

[config.linux]
type = "regex"
v_position = "\"rdmLinuxFallbackVersion\":\"([^\"]+)\""
d_position = "\"deb__x64\":\\{\"url\":\"(https://[^\"]+\\.deb)\""
