[info]
app_id = "USBDLM"
name = "USB Drive Letter Manager"
description = "Windows USB 盘符分配管理服务"
official_website = "https://www.uwe-sieber.de/usbdlm_e.html"
platforms = ["windows"]

[config]
type = "regex"
baseurl = "https://www.uwe-sieber.de"
url = "https://www.uwe-sieber.de/usbdlm_e.html"
v_position = "USBDLM V([\\d.]+)"
d_position = "(files/usbdlm_x64\\.zip)"
download_method = "browser"
