[info]
app_id = "dotnet9DRT"
name = ".NET 9 桌面运行时"
description = "Windows运行时"
official_website = "https://dotnet.microsoft.com/zh-cn/download/dotnet/9.0"
platforms = ["windows"]

[config]
type = "regex"
url = "https://dotnet.microsoft.com/zh-cn/download/dotnet/9.0"
baseurl = "https://dotnet.microsoft.com"

[config.windows]
v_position = "桌面运行时 (9\\.\\d+\\.\\d+)"
d_position = "href=\"(/zh-cn/download/dotnet/thank-you/runtime-desktop-[^\"]+-windows-x64-installer)\""
