[info]
app_id = "AssetStudio"
name = "AssetStudio"
description = "Unity解包工具"
status = ["已归档"]
official_website = "https://github.com/Perfare/AssetStudio/releases/"
platforms = ["windows"]

[config]
type = "github"
owner = "Perfare"
repo = "AssetStudio"

[config.windows]
d_position = "net6"
