[info]
app_id = "AutumnBox"
name = "AutumnBox"
status = ["Archived"]
description = "ADB工具"
official_website = "https://github.com/zsh2401/AutumnBox/releases"
platforms = ["windows"]

[config]
type = "json"
url = "https://api.github.com/repos/zsh2401/AutumnBox/releases"

[config.windows]
v_position = [0, "tag_name"]
d_position = [0, "assets", 0, "browser_download_url"]
