[info]
app_id = "AutumnBox"
name = "AutumnBox"
status = ["已归档"]
description = "ADB工具"
official_website = "https://github.com/zsh2401/AutumnBox/releases"
platforms = ["windows"]

[config]
type = "github"
owner = "zsh2401"
repo = "AutumnBox"
allow_prerelease = true

[config.windows]
d_position = "AutumnBox"
