[info]
app_id = "balenaEtcher"
name = "balenaEtcher"
description = "启动U盘烧写工具"
official_website = "https://github.com/balena-io/etcher/releases/"
platforms = ["windows", "macos", "linux"]

[config]
type = "github"
owner = "balena-io"
repo = "etcher"

[config.windows]
d_position = "Setup.exe"

[config.macos]
d_position = "arm64.dmg"

[config.linux]
d_position = "balena.*(linux|rpm|deb)"
