[info]
app_id = "DownKyiCore"
name = "DownKyiCore"
description = "Bilibili视频下载工具"
official_website = "https://github.com/yaobiao131/downkyicore/releases"
platforms = ["macos", "windows", "linux"]

[config]
type = "github"
owner = "yaobiao131"
repo = "downkyicore"

[config.macos]
d_position = "osx-arm64"

[config.windows]
d_position = "win-x64.zip"

[config.linux]
d_position = "x86_64.*rpm$|amd64.*deb$|x86_64.*AppImage$"
