[info]
app_id = "Ice"
name = "Ice"
description = "macOS菜单栏管理工具"
official_website = "https://github.com/jordanbaird/Ice/releases/"
platforms = ["macos"]

[config]
type = "github"
owner = "jordanbaird"
repo = "Ice"

[config.macos]
d_position = "zip"
