[info]
app_id = "jasmine"
name = "jasmine"
description = "神秘看图软件"
official_website = "https://github.com/ComicSparks/jasmine/releases"
platforms = ["macos", "windows", "linux", "ios", "android"]

[config]
type = "github"
owner = "ComicSparks"
repo = "jasmine"

[config.macos]
d_position = "dmg"

[config.windows]
d_position = "windows"

[config.linux]
d_position = "AppImage"

[config.ios]
d_position = "ipa"

[config.android]
d_position = "arm64.*apk"
