[info]
app_id = "rufus"
name = "rufus"
description = "烧写启动U盘工具"
official_website = "https://github.com/pbatard/rufus/releases"
platforms = ["windows"]

[config]
type = "github"
owner = "pbatard"
repo = "rufus"

[config.windows]
d_position = "^rufus-[0-9.]+\\.[0-9]+\\.exe$"
