[info]
app_id = "ZygiskNext"
name = "ZygiskNext"
description = "KernelSU 的 Zygisk 实现"
official_website = "https://github.com/LSPosed/ZygiskNext/releases"
platforms = ["android"]

[config]
type = "github"
owner = "LSPosed"
repo = "ZygiskNext"

[config.android]
d_position = "release"
