[info]
app_id = "ArCiela"
name = "Ar ciela"
description = "Ar ciela 字体"
official_website = "https://hymmnoserver.uguu.ca/"
platforms = ["font"]

[config]
type = "html_selector"
url = "https://hymmnoserver.uguu.ca/"
baseurl = "https://hymmnoserver.uguu.ca/"
v_position = { selector = "a[href*='ar-ciela_compartment.ttf']", regex = "TrueType Font \\(v([0-9.]+)\\)" }
d_position = { selector = "a[href*='ar-ciela_compartment.ttf']", attr = "href" }
